# .github/workflows/test-package.yml
name: Test Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Pack and test
        run: |
          pnpm pack
          mkdir -p releases
          mv *.tgz releases/

      - name: Create test project
        run: |
          mkdir test-project
          cd test-project
          # Create package.json with ES module support
          cat > package.json << 'EOF'
          {
            "name": "test-project",
            "version": "1.0.0",
            "type": "module",
            "scripts": {
              "test": "node test.js"
            }
          }
          EOF
          npm install typescript zod @types/node

      - name: Test installation
        run: |
          cd test-project
          npm install ../releases/result-ts-*.tgz

      - name: Test ES Module import
        run: |
          cd test-project
          cat > test.js << 'EOF'
          import { ok, err, Result } from 'result-ts';

          console.log('✅ Import successful');

          // Test basic functionality
          const result = ok("hello");
          console.log('✅ ok() works:', result);

          const error = err("failed");
          console.log('✅ err() works:', error);

          console.log('✅ All tests passed!');
          EOF
          node test.js

      - name: Test CommonJS require (alternative)
        run: |
          cd test-project
          cat > test-cjs.cjs << 'EOF'
          const { ok, err, Result } = require('result-ts');

          console.log('✅ CommonJS require successful');

          const result = ok("hello");
          console.log('✅ ok() works:', result);

          console.log('✅ CommonJS tests passed!');
          EOF
          node test-cjs.cjs

      - name: Test TypeScript
        run: |
          cd test-project
          cat > test.ts << 'EOF'
          import { ok, err, Result, isOk } from 'result-ts';

          function divide(a: number, b: number): Result<number, string> {
            return b === 0 ? err("Division by zero") : ok(a / b);
          }

          const result = divide(10, 2);
          if (isOk(result)) {
            console.log('✅ TypeScript test result:', result.value);
          }

          console.log('✅ TypeScript tests passed!');
          EOF
          npx tsx test.ts

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-tarball
          path: releases/*.tgz
